# Generated by Django 3.0.4 on 2020-03-18 20:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import movie_database.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1900), movie_database.models.max_value_current_year])),
                ('type', models.CharField(max_length=128, unique=True)),
                ('imdb_id', models.CharField(max_length=32, unique=True)),
                ('poster', models.TextField()),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
