# Generated by Django 3.0.4 on 2020-03-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_database', '0002_auto_20200318_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
