# Generated by Django 3.0.4 on 2020-03-19 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_database', '0003_movie_favourite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favourite',
        ),
    ]
